In [2]:
import numpy as np

In [66]:
#1 Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.
vector = np.arange(1,11)
print(vector)

[ 1  2  3  4  5  6  7  8  9 10]


In [67]:
#2 Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.
matrix = np.zeros((3, 3), dtype=int)
print(matrix)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [77]:
#3 Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.
matrix = np.random.randint(11, size=(5,5))
print(matrix)

[[ 5  3  7  7 10]
 [ 7  3  9  3  4]
 [ 4  5  3  5  5]
 [ 9 10  4  3  3]
 [ 1  9  8  0 10]]


In [78]:
#4 Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.
matrix = np.random.randint(2, size=(4,4))
print(matrix)

[[1 0 0 0]
 [1 0 0 1]
 [0 1 0 0]
 [1 0 0 0]]


In [99]:
#5 Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.
vector_1 =  np.array([np.random.randint(1,11) for n in range(5)])
vector_2 =  np.array([np.random.randint(1,11) for n in range(5)])
print(vector_1 - vector_2)
print(vector_1 + vector_2)
print(vector_1 * vector_2)

[ 4  0  5 -1  3]
[14 20 15 15 13]
[ 45 100  50  56  40]


In [104]:
#6 Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.
vector_1 =  np.array([np.random.randint(0,100) for n in range(7)])
vector_2 =  np.array([np.random.randint(0,100) for n in range(7)])
print(vector_1 * vector_2)

[1683 5460  714 2632  297 5076 2470]


In [118]:
#7 Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.
matrix_2x2 = np.array(np.random.randint(1,11, size=(2,2)))
matrix_2x3 = np.array(np.random.randint(1,11, size=(2,3)))
result = np.dot(matrix_2x2, matrix_2x3)
print(result)

[[26 42 68]
 [24 30 52]]


In [120]:
#8 Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.
matrix = np.array(np.random.randint(0,100, size=(3,3)))
matrix_inv = np.linalg.inv(matrix)
print(matrix)
print(matrix_inv)

[[24 49 72]
 [44 55 59]
 [95 41 60]]
[[-0.01102863 -0.00015022  0.01338207]
 [-0.03711678  0.06759886 -0.02193208]
 [ 0.04282513 -0.04595471  0.01046531]]


In [122]:
#9 Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.
matrix = np.array(np.random.randint(0,2, size=(4,4)))
matrix_T = matrix.T
print(matrix)
print(matrix_T)

[[0 0 1 1]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 1 1]]
[[0 0 0 0]
 [0 1 1 1]
 [1 0 0 1]
 [1 0 0 1]]


In [126]:
#10 Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.
matrix = np.array(np.random.randint(1,11, size=(3,4)))
vector = np.array([np.random.randint(1,11) for n in range(4)])
print(matrix * vector)

[[42 25 35  4]
 [12 50 56 16]
 [54 15 35 16]]


In [127]:
#11 Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.
matrix = np.array(np.random.randint(0,2, size=(2,3)))
vector = np.array([np.random.randint(0,2) for n in range(3)])
print(matrix * vector)

[[0 1 0]
 [0 1 0]]


In [131]:
#12 Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.
matrix_1 = np.array(np.random.randint(1,11, size=(2,2)))
matrix_2 = np.array(np.random.randint(1,11, size=(2,2)))
print(matrix_1 * matrix_2)

[[36 24]
 [18 60]]


In [132]:
#13 Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.
matrix_1 = np.array(np.random.randint(1,11, size=(2,2)))
matrix_2 = np.array(np.random.randint(1,11, size=(2,2)))
result = np.dot(matrix_1, matrix_2)
print(result)

[[ 72  53]
 [108  86]]


In [4]:
#14 Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.
matrix = np.array(np.random.randint(1,101, size=(5,5)))
print(matrix.sum())

1059


In [5]:
#15 Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.
matrix_1 = np.array(np.random.randint(1,11, size=(4,4)))
matrix_2 = np.array(np.random.randint(1,11, size=(4,4)))
print(matrix_1 - matrix_2)

[[ 0  9  3  3]
 [-1 -5  1 -3]
 [ 2  4 -4  2]
 [ 1  3  0 -3]]


In [18]:
#16 Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.
matrix = np.array(np.random.randint(0,2, size=(3,3)))
vector = np.array([matrix[0].sum(), matrix[1].sum(), matrix[2].sum()])
print(vector)

[0 3 2]


In [29]:
#17 Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.
matrix = np.array(np.random.randint(0,3, size=(3,4)))

vector_1 = matrix[0]
vector_2 = matrix[1]
vector_3 = matrix[2]

def func_sqr(vector):
  list = []
  for i in vector:
    list.append(i**2)
  return list

matrix_sqr = np.array( [ func_sqr(vector_1), func_sqr(vector_2), func_sqr(vector_3) ] )

print(matrix_sqr)

[[4 0 1 0]
 [0 4 4 4]
 [1 4 4 1]]


In [34]:
#18 Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.
vector = np.array([np.random.randint(1,51) for n in range(4)])
vector_new = np.array([vector[0]**0.5, vector[1]**0.5, vector[2]**0.5, vector[3]**0.5], dtype=float)
print(vector_new)

[49  6 28 15]
[7.         2.44948974 5.29150262 3.87298335]
