Підготовка датасету

In [100]:
# імпорт бібліотек
import shutil
import glob
import os
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt 
from sklearn.model_selection import train_test_split 
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix 
from sklearn.tree import DecisionTreeClassifier

In [ ]:
# розпаковка архіву
archive_name =  'homework.zip'
shutil.unpack_archive(archive_name, 'dataset')

In [58]:
# допоміжна функція для сканування каталогів idle, running, stairs, walking 
# в кореневому каталозі dateset/data
# і обєднання файлів що містяться в них в 4 окремі файли згідно їх класів (idle, running, stairs, walking)


def union_file(mycsvdir, file_name):
  mycsvdir = mycsvdir

  csvfiles = glob.glob(os.path.join(mycsvdir, '*.csv'))

  dataframes = []  
  for csvfile in csvfiles:
      df = pd.read_csv(csvfile)
      dataframes.append(df)

  result.to_csv(file_name, index=False)

In [80]:
# запуск union_file
union_file('dataset/data/idle', 'idle.csv')
union_file('dataset/data/running', 'running.csv')
union_file('dataset/data/stairs', 'stairs.csv')
union_file('dataset/data/walking', 'walking.csv')

In [82]:
# додавання в кожен файл класу і обєднання їх в один файл dataset_accelerator
i = pd.read_csv('idle.csv')
r = pd.read_csv('running.csv') 
s = pd.read_csv('stairs.csv')
w = pd.read_csv('walking.csv')

i.insert(3, 'class', 'idle')
r.insert(3, 'class', 'running')
s.insert(3, 'class', 'stairs')
w.insert(3, 'class', 'walking')

all_class = pd.concat([i, r, s, w])

all_class.to_csv('dataset_accelerator.csv', encoding='utf8')

Побудова моделі SVM

In [85]:
# завантажуємо вже підготовлений датасет
accelerator = pd.read_csv('dataset_accelerator.csv')

In [86]:
accelerator.head()

Unnamed: 0  accelerometer_X  accelerometer_Y  accelerometer_Z class
0           0        -0.263362         4.769250         8.250419  idle
1           1        -0.268151         5.204995         8.125921  idle
2           2        -0.435745         5.434838         7.972692  idle
3           3        -0.244209         5.592855         8.451532  idle
4           4         0.244209         5.626374         7.843405  idle

In [87]:
# первинна обробка датасету, створюємо дві змінні, X - параметри  y - окремо класи.
X = accelerator.drop('class', axis=1) 
y = accelerator['class']

In [93]:
# розділення даних на тестові та тренувальні
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20)

In [94]:
# Поліноміальне ядро (навчання моделі)
svclassifier = SVC(kernel='poly', degree=8) 
svclassifier.fit(X_train, y_train)

SVC(degree=8, kernel='poly')

In [95]:
# прогнози на основі тестових даних  
y_pred = svclassifier.predict(X_test)

In [98]:
# оцінка алгоритма
print(confusion_matrix(y_test, y_pred)) 
print(classification_report(y_test, y_pred))

[[   0    1  515 5854]
 [   0    0  490 5711]
 [   0    2  461 5744]
 [   0    1  478 5679]]


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


              precision    recall  f1-score   support

        idle       0.00      0.00      0.00      6370
     running       0.00      0.00      0.00      6201
      stairs       0.24      0.07      0.11      6207
     walking       0.25      0.92      0.39      6158

    accuracy                           0.25     24936
   macro avg       0.12      0.25      0.13     24936
weighted avg       0.12      0.25      0.12     24936



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Побудова моделі Decision Tree

In [101]:
classifier = DecisionTreeClassifier()
classifier.fit(X_train, y_train)


DecisionTreeClassifier()

In [102]:
y_pred = classifier.predict(X_test)

In [103]:
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[  35 5096 1037  202]
 [4954    8 1037  202]
 [4977 1025    3  202]
 [4960 1001  196    1]]
              precision    recall  f1-score   support

        idle       0.00      0.01      0.00      6370
     running       0.00      0.00      0.00      6201
      stairs       0.00      0.00      0.00      6207
     walking       0.00      0.00      0.00      6158

    accuracy                           0.00     24936
   macro avg       0.00      0.00      0.00     24936
weighted avg       0.00      0.00      0.00     24936



In [104]:
# ядро Гауса

svclassifier = SVC(kernel='rbf') 
svclassifier.fit(X_train, y_train)

SVC()

In [105]:
y_pred = svclassifier.predict(X_test)

In [106]:
print(confusion_matrix(y_test, y_pred)) 
print(classification_report(y_test, y_pred))

[[   0 4037  915 1418]
 [   0 3934  905 1362]
 [   0 4039  866 1302]
 [   0 3993  867 1298]]


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


              precision    recall  f1-score   support

        idle       0.00      0.00      0.00      6370
     running       0.25      0.63      0.35      6201
      stairs       0.24      0.14      0.18      6207
     walking       0.24      0.21      0.22      6158

    accuracy                           0.24     24936
   macro avg       0.18      0.25      0.19     24936
weighted avg       0.18      0.24      0.19     24936



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
